config/routes.rb
Rails.application.routes.draw do
  resources :areas

  resources :clubs

root 'clubs#index'

end

app/models/area.rb
class Area < ActiveRecord::Base
end

app/models/club.rb
class Club < ActiveRecord::Base
 # validates_length_of :name,
 #  { minimum: 5, message: "" }
 #  validates :name, presence: true, length: {maximum:10, message:""}

 def animSpeed(people, capacity)

  if people.nil?
    people = 0
  end
  if capacity.nil? || capacity < 1
    capacity = 100
  end

 hb = (people.to_f/capacity)

 if hb < 0.1
	hb = 0.1
elsif hb > 0.8
	hb = 0.80
end

return 1.0-hb

 end


def heartbeat(people,capacity)
  if people == nil
    people = 0
  end
  if capacity == nil || capacity < 1
    capacity = 100
  end
 hb = ((people.to_f/capacity)*100)
if hb > 80
  return "Insane!"
elsif hb > 60
  return "Party Rock!"
elsif hb > 40
  return "Chilling"
elsif hb > 20
  return "Almost empty come with friends!"
elsif hb >  10
  return "Definitely come with friends or else you are on your own"
elsif hb == 2
  return ""
elsif hb == 3
  return "LETS GET HIGH"
elsif hb == 4
  return "GETTING F*CKING WEIRD"
elsif hb == 5
  return "TONIGHT IS GONNA BE A GOOD NIGHT"
elsif hb == 6
  return "WILD ON"
elsif hb == 7
  return "OF THE HOOK"
elsif hb == 8
  return "GET READY FOR TONIGHT"
elsif hb == 9
  return "ITS FUCKING INSANE"
else
  "The place is close as of now"
end
end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :set_area, only: [:show, :edit, :update, :destroy]

  # GET /areas
  # GET /areas.json
  def index
    @areas = Area.all
  end

  # GET /areas/1
  # GET /areas/1.json
  def show
  end

  # GET /areas/new
  def new
    @area = Area.new
  end

  # GET /areas/1/edit
  def edit
  end

  # POST /areas
  # POST /areas.json
  def create
    @area = Area.new(area_params)

    respond_to do |format|
      if @area.save
        format.html { redirect_to @area, notice: 'Area was successfully created.' }
        format.json { render :show, status: :created, location: @area }
      else
        format.html { render :new }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /areas/1
  # PATCH/PUT /areas/1.json
  def update
    respond_to do |format|
      if @area.update(area_params)
        format.html { redirect_to @area, notice: 'Area was successfully updated.' }
        format.json { render :show, status: :ok, location: @area }
      else
        format.html { render :edit }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /areas/1
  # DELETE /areas/1.json
  def destroy
    @area.destroy
    respond_to do |format|
      format.html { redirect_to areas_url, notice: 'Area was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_area
      @area = Area.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def area_params
      params[:area]
    end
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  before_action :set_club, only: [:show, :edit, :update, :destroy]

  # GET /clubs
  # GET /clubs.json
  def index
    @clubs = Club.all

  # @clubs = Club.where id:1
  # @clubs = Club.where id:2
  end


  # GET /clubs/1
  # GET /clubs/1.json
  def show

  end

  # GET /clubs/new
  def new
    @club = Club.new
  end

  # GET /clubs/1/edit
  def edit
  end

  # POST /clubs
  # POST /clubs.json
  def create
    @club = Club.new(club_params)

    respond_to do |format|
      if @club.save
        format.html { redirect_to @club, notice: 'Club was successfully created.' }
        format.json { render :show, status: :created, location: @club }
      else
        format.html { render :new }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clubs/1
  # PATCH/PUT /clubs/1.json
  def update
    respond_to do |format|
      if @club.update(club_params)
        format.html { redirect_to @club, notice: 'Club was successfully updated.' }
        format.json { render :show, status: :ok, location: @club }
      else
        format.html { render :edit }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clubs/1
  # DELETE /clubs/1.json
  def destroy
    @club.destroy
    respond_to do |format|
      format.html { redirect_to clubs_url, notice: 'Club was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_club
      @club = Club.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def club_params
      params.require(:club).permit(:name, :address, :hours, :phone, :people, :capacity)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper

end

app/views/areas/_form.html.erb
<%= form_for(@area) do |f| %>
  <% if @area.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@area.errors.count, "error") %> prohibited this area from being saved:</h2>

      <ul>
      <% @area.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/areas/edit.html.erb
<h1>Editing area</h1>

<%= render 'form' %>

<%= link_to 'Show', @area %> |
<%= link_to 'Back', areas_path %>

app/views/areas/index.html.erb
<h1>Listing areas</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @areas.each do |area| %>
      <tr>
        <td><%= link_to 'Show', area %></td>
        <td><%= link_to 'Edit', edit_area_path(area) %></td>
        <td><%= link_to 'Destroy', area, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Area', new_area_path %>

app/views/areas/new.html.erb
<h1>New area</h1>

<%= render 'form' %>

<%= link_to 'Back', areas_path %>

app/views/areas/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_area_path(@area) %> |
<%= link_to 'Back', areas_path %>

app/views/clubs/_form.html.erb
<%= form_for(@club) do |f| %>
  <% if @club.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@club.errors.count, "error") %> prohibited this club from being saved:</h2>

      <ul>
      <% @club.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="centered">
<div class="row">
<div class="four columns centered field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  </div>
  <div class="row">
  <div class="four columns centered field">
      <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  </div>
  <div class="row">
  <div class="four columns centered field">
    <%= f.label :hours %><br>
    <%= f.text_field :hours %>
</div>
</div>
<div class="row">
<div class="four columns centered field">
    <%= f.label :phone %> <br>
    <%= f.text_field :phone %>
  </div>
  </div>
  <div class="row">
  <div class="four columns centered field">
    <%= f.label :people %><br>
    <%= f.text_field :people %>
  </div>
  </div>
  <div class="row">
  <div class="four columns centered field">
    <%= f.label :capacity %><br>
    <%= f.text_field :capacity %>
  </div>
  </div>
<div class="actions">
    <%= f.submit %>
  </div>
</div>
<% end %>



<%= link_to 'New Club', new_club_path %>
<!-- <%= link_to 'Show', @club %> | -->

app/views/clubs/edit.html.erb
<h1>Editing club</h1>

<%= render 'form' %>

<%= link_to 'Show', @club %> |
<%= link_to 'Back', clubs_path %>
<%= link_to 'Delete', {:action => 'destroy'}, :method => :delete %>

app/views/clubs/index.html.erb
<!-- ESTE AQUI ES LO QUE VES EN LOCALHOST -->
<!--section id="wrapper" style="box-shadow: rgb(0, 0, 0) 0px 0px 150px inset;"-->

<div class='row' id='logo'>
	<div class="six columns centered">
<%= image_tag 'tagline_heartbeat.png' %>
<%= image_tag 'heart_heartbeat.png' %>
</div>
</div>
	<h2 class='city'><span class="pe-7s-map-marker pe-2x pe-va"></span><br>MIAMI</h2>
	<% @clubs.each do |club| %>
		<section class='club_par'>
			<div class='row'>
				<div class="twelve columns club_item">
					<h2 class="ClubName"><%= club.name %></h2>
					<h2 class="MoodBeat">Heartbeat Mood</h2>
				<!--	 <h2 class="h2c"><%=club.mood%></h2> -->
					<h2 class="h2c"><%=club.heartbeat(club.people,club.capacity) %></h2>
					  <li class="ClubAddress" align="center"><%= club.address %></li>
					  <li class="ClubAddress"><%= club.hours %></li>
					  <li class="ClubAddress extra_space"><%= club.phone %></li>

					<!--	<%= image_tag 'heart_heartbeat.png', style:"max-width: 250px; animation-duration: 0.1s;
						-webkit-animation-duration: 0.2s;
						-webkit-filter: grayscale(10)", class:'animated pulse-slow infinite' %> -->

				<%= image_tag 'heart_heartbeat.png', style:"max-width: 250px; animation-duration: #{club.animSpeed(club.people, club.capacity)}s;
						-webkit-animation-duration: #{club.animSpeed(club.people, club.capacity)}s;
						-webkit-filter: grayscale(#{club.animSpeed(club.people, club.capacity)})", class:'animated pulse-slow infinite' %>

				</div>
			</div>
		</section>
	<% end %>


<!-- <h1>Listing clubs</h1>
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clubs.each do |club| %>
      <tr>
        <td><%= link_to 'Show', club %></td>
        <td><%= link_to 'Edit', edit_club_path(club) %></td>
        <td><%= link_to 'Destroy', club, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
-->

<!-- <%= link_to 'New Club', new_club_path %>
<%= link_to 'Back', clubs_path %> -->
<!--/section-->

app/views/clubs/new.html.erb
<div align="center" class="new-club">
<h1>New club</h1>

<%= render 'form' %>

<%= link_to 'Back', clubs_path %>

</div>

app/views/clubs/show.html.erb
<p id="notice"><%= notice %></p>

<%= @club.name %>
<%= link_to 'Edit', edit_club_path(@club) %> |
<%= link_to 'Back', clubs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Heartbeat</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-47849197-2', 'auto');
  ga('send', 'pageview');

</script>
</body>

</html>